### ISSUE TITLE
LDAP support?

### ISSUE THREAD

**Issue by ccwang002** [ogham/rust-users#14]
My server at work uses a LDAP/SSSD (System Security Services Daemon) setup and in this case, `exa` cannot find the name of uid and gid, so only the uid and gid were reported. 

Sorry I didn't know much about the mechanism of such name retrieval nor the LDAP setup. But I'd like to report here so someone with sufficient background can take over the issue. 

Thanks for the wonderful tool you built :)

**Comment by ogham** [comment]
Thanks!

I'm afraid I don't know much about LDAP either -- not even enough to say that it would map cleanly onto the same interface used by Unix (get user by ID, get user by name). There's a Rust LDAP implementation over at https://github.com/inejge/ldap3; it might be possible to use the `Users` trait to connect the two.

Also:

> exa cannot find the name of uid and gid, so only the uid and gid were reported.

This sounds really annoying. A temporary solution might be for exa to provide a way to customise usernames, so instead of having to talk to an LDAP server, it could just call user 1000 "you" or something.

**Comment by ccwang002** [comment]
Thanks for your reply! I don't mind having just uid/gid for now since exa works perfectly fine in all the other cases.

**Comment by tatref** [comment]
Hi,

That an old thread, but `users` uses `libc::getpwuid_r`
https://github.com/ogham/rust-users/blob/d6883b4cc1bf00fdca920f5064ea551684fc0faf/src/base.rs#L336

From the doc (https://linux.die.net/man/3/getpwuid_r)

> The getpwnam() function returns a pointer to a structure containing the broken-out fields of the record in the password database (e.g., the local password file /etc/passwd, NIS, and LDAP) that matches the username name. 

So LDAP or NIS should work properly. The databases resolution order is defined in `/etc/nsswitch.conf`. The simplest way to test is with `getent` (this will access all databases)

    $ getent passwd 54321
    oracle:x:54321:54321::/home/oracle:/bin/bash

The output is similar to `grep oracle /etc/passwd`, but works for all NIS, LDAP...

You can use `ltrace` to show that it indeed uses `getpwuid`

```
$ ltrace getent passwd 54321
mtrace()                                                                    = <void>
setlocale(LC_ALL, "")                                                       = "en_US.UTF-8"
textdomain("libc")                                                          = "libc"
argp_parse(0x5582aacde140, 3, 0x7ffc41647578, 0)                            = 0
strcmp("passwd", "passwd")                                                  = 0
__errno_location()                                                          = 0x7fea07fcf4c0
strtoul(0x7ffc416493e0, 0x7ffc41647400, 10, 0xff7fffc0)                     = 0xd431
getpwuid(0xd431, 0x7ffc416493e4, 0x7ffc416493e5, 0)                         = 0x7fea07db74a0        <======
```

**Comment by ccwang002** [comment]
Wow many thanks for providing insights to an old issue! It seems to me that `getpwuid_r` was introduced in commit https://github.com/ogham/rust-users/commit/5bf7463b726963117adc5826913672d41c677eae, so maybe this issue has been fixed already! I will test it next week and report here.

**Comment by ccwang002** [comment]
I tested this on exa v0.9 and v0.10.1 (latest) linked to gnu and musl C lib on linux. Indeed, the gnu build of the latest exa no long has problems resolving user and group names. But the musl build of both versions are still unable to do so.

More specifically, here's the output of different versions and builds:

```
# all outputs use the same command `exa -l -lg`
# v0.10.1 with glibc (both user and group names are correctly shown)
drwxrwsr-x - lwang gsc 26 Apr 11:00 bin
drwxrwsr-x - lwang gsc 26 Apr 11:00 completions
drwxrwsr-x - lwang gsc 26 Apr 11:00 man

# v0.10.1 with musl
drwxrwsr-x - 13455 10001 26 Apr 11:00 bin
drwxrwsr-x - 13455 10001 26 Apr 11:00 completions
drwxrwsr-x - 13455 10001 26 Apr 11:00 man

# v0.9.0 with glibc (only user names are correctly shown)
drwxrwsr-x - lwang 10001 26 Apr 11:00 bin
drwxrwsr-x - lwang 10001 26 Apr 11:00 completions
drwxrwsr-x - lwang 10001 26 Apr 11:00 man

# v0.9.0 with musl
drwxrwsr-x - 13455 10001 26 Apr 11:00 bin
drwxrwsr-x - 13455 10001 26 Apr 11:00 completions
drwxrwsr-x - 13455 10001 26 Apr 11:00 man
```

So I think this issue is technically fixed?  It seems like musl only queries `/etc/passwd` ([ref](https://skarnet.org/software/nsss/)), so this is more of a limitation of using musl.

**Comment by ccwang002** [comment]
thanks again @tatref for your help! I will close this issue for now.
