### ISSUE TITLE
c_passwd struct layout

### ISSUE THREAD

**Issue by 1wilkens** [ogham/rust-users#3]
Hey while I was trying to add home directory and shell support to the library I noticed the struct layout of `c_passwd` did not match the one defined on my system (Arch Linux).

I don't know whether that layout is actually different on your machine or if it was just an oversight since you did not use the values yet. Anyways I added `home_dir` and `shell` to the `User` struct on my fork and fixed the struct layout if you want to take a look.

**Comment by ogham** [comment]
Fixed in #4!
