### ISSUE TITLE
Group Name not (always) shown in --long listings in exa 0.9.0

### ISSUE THREAD

**Issue by sklages** [ogham/rust-users#40]
This is still an issue with `MOST RECENT VERSION: v0.9.0, released on July 15th`, see https://github.com/ogham/exa/issues/671

```
 $ exa --version
exa v0.9.0
```

Any solution for that yet? It is not for all files / directories. 

I just discovered `exa` and really like it, but this issue would be a real game stopper for me, .. working in a multi-server/multi-user linux environment ...

**Comment by max-heller** [comment]
Probably blocked on #38

**Comment by sklages** [comment]
@max-heller .. thanks .. hmm, and what does this mean for fixing of this issue? I am not a developer so please have patience with me ;-)

**Comment by max-heller** [comment]
@sklages if it is the culprit, the PR being merged might resolve this issue
